# Generated by Django 4.1.4 on 2023-02-10 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Homepage', '0002_alter_datasettext_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='datasettext',
            name='is_estimated',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='datasettext',
            name='is_garbage',
            field=models.IntegerField(default=0),
        ),
    ]
