# Generated by Django 4.1.4 on 2023-02-11 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Homepage', '0003_datasettext_is_estimated_datasettext_is_garbage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datasettext',
            name='is_estimated',
            field=models.FloatField(default=0),
        ),
    ]
